# This is a good template, but disabled for now
# "Settings>General: Visibility, project features, permissions -> Repositry: CI"

image: mambaorg/micromamba:latest

variables:
    MAMBA: micromamba --yes --quiet
    SNAKEMAKE: snakemake --cores=1

before_script:
    - $MAMBA install -c conda-forge -c bioconda snakemake
    - $SNAKEMAKE --lint

dry-run:
    script:
        - $SNAKEMAKE --dry-run