general:
  log:
    level: info

observations:
  datastore: build/crab_sample/dl3
  obs_time:
    start: null
    stop: null
  required_irf:
    - aeff
    - edisp

datasets:
  type: 3d
  stack: false
  geom:
    wcs:
      skydir: { frame: icrs, lon: 83.633 deg, lat: 22.014 deg }
      binsize: 0.02 deg
      width: { width: 2.0 deg, height: 2.0 deg }
      binsize_irf: 0.2 deg
    selection: { offset_max: 2.5 deg }
    axes:
      energy:
        min: 500 GeV
        max: 50 TeV
        nbins: 10
      energy_true:
        min: 500 GeV
        max: 50 TeV
        nbins: 5
  background:
    method: "fov_background"
      #    exclusion: "build/crab_sample/analysis-example/exclusion.fits.gz"
      #    I set that elsewhere
    parameters: {"method": "fit"}
  safe_mask:
    methods: ["aeff-max"]
    parameters: {aeff_percent: 30}
  on_region:
    { frame: icrs, lon: 83.633 deg, lat: 22.014 deg, radius: 0.3 deg }
  containment_correction: false

fit:
  fit_range: { min: 20 GeV, max: 10 TeV }

flux_points:
  energy: { min: 1000 GeV, max: 10 TeV, nbins: 20 }
  source: Crab

light_curve:
  energy_edges: { min: 1000 GeV, max: 10 TeV, nbins: 1 }
  source: Crab
