components:
  - name: M87
    type: SkyModel
    spectral:
      type: PowerLawSpectralModel
      parameters:
        - name: amplitude
          value: 6.0e-11
          unit: cm-2 s-1 TeV-1
          min: 0
        - name: index
          value: 2.2
          unit: ""
        - name: reference
          value: 100
          unit: GeV
          frozen: true
    spatial:
      type: PointSpatialModel
      frame: icrs
      parameters:
        - frozen: false
          max: 188.0
          min: 187.4
          name: lon_0
          scale: 1.0
          unit: deg
          value: 187.70593076
        - frozen: false
          max: 12.8
          min: 12
          name: lat_0
          scale: 1.0
          unit: deg
          value: 12.39112329
